### ISSUE TITLE
运行不了 KeyError

### ISSUE THREAD

**Issue by viocha** [AuYang261/BIT_yanhe_download#2]
```
Traceback (most recent call last):
  File "D:\IT\git\cloned\BIT_yanhe_download\main.py", line 2, in <module>
    import m3u8dl
  File "D:\IT\git\cloned\BIT_yanhe_download\m3u8dl.py", line 21, in <module>
    from signature_from_js import signature_from_js
  File "D:\IT\git\cloned\BIT_yanhe_download\signature_from_js.py", line 5, in <module>
    from js2py.pyjs import *
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
```

**Comment by AuYang261** [comment]
我这里试的是可以的，你是用的release里的可执行文件下的嘛

**Comment by viocha** [comment]
https://www.yanhekt.cn/course/45497
编号：45497

> 我这里试的是可以的，你是用的release里的可执行文件下的嘛

**Comment by viocha** [comment]
参考这个issue
https://github.com/GDDG08/YanHeKT_Downloader/issues/5#issuecomment-2030161128

**Comment by AuYang261** [comment]
> 参考这个issue [GDDG08/YanHeKT_Downloader#5 (comment)](https://github.com/GDDG08/YanHeKT_Downloader/issues/5#issuecomment-2030161128)

感谢！

**Comment by AuYang261** [comment]
@viocha 问题已修复
